name = "FormalGrammars"
uuid = "5857bfb6-b7fa-11e9-20ef-f35bf60ce067"
authors = ["David Ellison <davidehellison@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
